---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Mld.
--- DateTime: 15/07/2021 21:05
---

CHelper = {};

function CHelper.DisplayLocationNotification(text, location, duration)
    exports["baphomet"]:DisplayLocationNotification(text, location, duration)
end

function CHelper.DisplayLeftNotification(title, subTitle, iconDict, icon, duration)
    exports["baphomet"]:DisplayLeftNotification(title, subTitle, iconDict, icon, duration)
end
