---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Mld.
--- DateTime: 15/07/2021 21:05
---

CHelper = {};

function CHelper.NoClip(IsChecked)
    if (IsChecked) then
        if (Global.CameraNoClip == nil) then
            Global.CameraNoClip = CreateCamera(GetHashKey("DEFAULT_SCRIPTED_CAMERA"), true)
        end
        SetCamActive(Global.CameraNoClip, true)
        SetCamCoord(Global.CameraNoClip, GetEntityCoords(Player.PedId))
        RenderScriptCams(true, false, 0, true, true)
        FreezeEntityPosition(Player.PedId, true)
        SetEntityInvincible(Player.PedId, true)
        SetEntityVisible(Player.PedId, false)
        Player.IsInNoClip = true
    end
    if not (IsChecked) then
        local CAM_COORDS = GetCamCoord(Global.CameraNoClip)
        DestroyCam(Global.CameraNoClip)
        RenderScriptCams(false, false, 0, false, false)
        FreezeEntityPosition(Player.PedId, false)
        SetEntityCoords(Player.PedId, CAM_COORDS.x, CAM_COORDS.y, CAM_COORDS.z)
        SetEntityInvincible(Player.PedId, false)
        SetEntityVisible(Player.PedId, true)
        if (Global.CameraNoClip) then
            Global.CameraNoClip = nil;
        end
        Player.IsInNoClip = false
    end
end

function CHelper.KeyboardInput(TextEntry, ExampleText, OnlyNumber)
    AddTextEntry('FMMC_KEY_TIP1', TextEntry)
    DisplayOnscreenKeyboard(1, "FMMC_KEY_TIP1", "", ExampleText, "", "", "", 500)
    local blocking = true

    while UpdateOnscreenKeyboard() ~= 1 and UpdateOnscreenKeyboard() ~= 2 do
        Citizen.Wait(0)
    end

    if UpdateOnscreenKeyboard() ~= 2 then
        local result = GetOnscreenKeyboardResult()
        Citizen.Wait(500)
        blocking = false
        if (OnlyNumber) then
            local number = tonumber(result)
            if (number ~= nil) then
                return number
            end
            return nil
        else
            return result
        end
    else
        Citizen.Wait(500)
        blocking = false
        return nil
    end
end


